
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/flask_api_exam
    env_file:
      - .env
    depends_on:
      - db
  test:
    image: python:3.10-slim
    volumes:
      - .:/flask_api_exam
    working_dir: /flask_api_exam
    command: sh -c "pip install -r requirements.txt && pytest tests"


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
          - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
